# Generated by Django 4.2.6 on 2023-10-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getdata',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='getdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='getdata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='getdata',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='getdata',
            name='lives_in',
        ),
        migrations.AlterField(
            model_name='getdata',
            name='nick_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
